Hesca/urls.py
from django.urls import include, path

urlpatterns = [
    path("main/", include("main.urls")),
]

main/urls.py
from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("kanto", views.kanto, name="kanto"),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404


# Create your views here.
def index(request):
    return render(request, "main/index.html")

def kanto(request):
    return render(request, "main/kanto.html")

main/templates/main/contact.html
<!DOCTYPE HTML>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>ホームページ・タイトル</title>
<meta name="viewport" content="width=device-width">
<meta name="keywords" content="キーワード">
<meta name="description" content="紹介文">
<link rel="stylesheet" href="css/sp.css">
<link rel="stylesheet" href="css/pc.css">
<!--[if lt IE 9]>
<script src="js/html5.js"></script>
<script src="js/css3-mediaqueries.js"></script>
<![endif]-->

</head>

<body>

<!-- メイン -->

<div id="main">


<!-- ヘッダー -->

<div id="header">

<h1>こちらには、メインキーワードや紹介文を入れてください</h1>

  <div id="header_inner">
   <div id="h_logo"><h2><a href="index.html">テンプレートカンパニー</a></h2></div>
   <div id="h_info">
<p class="tel">TEL. 00-0000-0000</p>
<p>営業時間 AM10:00 ～ PM20:00</p>
</div>
  </div>

</div>

<div id="header-menu">
  <ul class="clearfix">
    <li class="home"><a href="index.html">ホーム<br /><span class="sub">home</span></a></li>
    <li><a href="goaisatu.html">ご挨拶<br /><span class="sub">goaisatu</span></a></li>
    <li><a href="information.html">業務内容<br /><span class="sub">infomation</span></a></li>
    <li><a href="profile.html">会社概要<br /><span class="sub">profile</span></a></li>
    <li><a href="faq.html">よくあるご質問<br /><span class="sub">faq</span></a></li>
    <li><a href="contact.html">お問い合わせ<br /><span class="sub">contact</span></a></li>
   </ul>
</div>


<!-- メイン画像 ここから -->
<div id="header-img">
<img src="img/head_img_slim.png" alt="head_img_slim" class="main_photo">
</div>
<!-- メイン画像 ここまで -->




<!-- ヘッダー終わり -->


<!-- コンテンツ -->

<!-- メインコンテンツ -->

<div id="container">
  <div id="contents">


<div id="pannavi">
<a href="index.html">HOME</a> &gt; お問い合わせページ
</div>




<h2 class="page_title">お問い合わせ</h2>

<p>メールでのお問い合わせは、下記アドレスまでお願い致します。追ってご連絡させていただきます。お手数ですが、どうぞよろしくお願い致します。</p>

<p>E-mail ： info@aaaaa.com</p>

<hr class="line">

<p>&nbsp;</p>






<h2>お問い合わせはコチラ</h2>

<div class="gray_bg_contact">

<p><img src="img/icon.gif" alt="icon"> <b>電話番号</b>： <span class="red_b">00-0000-0000</span>　<img src="img/icon.gif" alt="icon"> <b>FAX</b>： <span class="red_b">00-0000-0000</span><br>
ご不明な点がございましたら、まずはお気軽にご相談下さい。</p>

</div>






<hr class="line">

<p class="back"><a href="#header"><img class="scroll" src="img/pagetop.png" alt="ページトップに戻る"></a></p>

<br>


  </div>

<!-- メインコンテンツ終わり -->

</div>

<!-- コンテンツ終わり -->

<!-- フッター -->

<div id="footer">
<a href="index.html">ホーム</a>　|　<a href="goaisatu.html">ご挨拶</a>　|　<a href="information.html">業務内容</a>　|　<a href="profile.html">会社概要</a>　|　<a href="faq.html">よくあるご質問</a>　|　<a href="contact.html">お問い合わせ</a>　|　<a href="link.html">リンク</a>　|　<a href="sitemap.html">サイトマップ</a>
<br>
<br>
Copyright (C) 20xx SITE NAME All Rights Reserved.　design by <a href="http://tempnate.com/" target="_blank">tempnate</a>
</div>

<!-- フッター終わり -->

</div>

<!-- メイン終わり -->

</body>
</html>

main/templates/main/faq.html
<!DOCTYPE HTML>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>ホームページ・タイトル</title>
<meta name="viewport" content="width=device-width">
<meta name="keywords" content="キーワード">
<meta name="description" content="紹介文">
<link rel="stylesheet" href="css/sp.css">
<link rel="stylesheet" href="css/pc.css">
<!--[if lt IE 9]>
<script src="js/html5.js"></script>
<script src="js/css3-mediaqueries.js"></script>
<![endif]-->

</head>

<body>

<!-- メイン -->

<div id="main">


<!-- ヘッダー -->

<div id="header">

<h1>こちらには、メインキーワードや紹介文を入れてください</h1>

  <div id="header_inner">
   <div id="h_logo"><h2><a href="index.html">テンプレートカンパニー</a></h2></div>
   <div id="h_info">
<p class="tel">TEL. 00-0000-0000</p>
<p>営業時間 AM10:00 ～ PM20:00</p>
</div>
  </div>

</div>

<div id="header-menu">
  <ul class="clearfix">
    <li class="home"><a href="index.html">ホーム<br /><span class="sub">home</span></a></li>
    <li><a href="goaisatu.html">ご挨拶<br /><span class="sub">goaisatu</span></a></li>
    <li><a href="information.html">業務内容<br /><span class="sub">infomation</span></a></li>
    <li><a href="profile.html">会社概要<br /><span class="sub">profile</span></a></li>
    <li><a href="faq.html">よくあるご質問<br /><span class="sub">faq</span></a></li>
    <li><a href="contact.html">お問い合わせ<br /><span class="sub">contact</span></a></li>
   </ul>
</div>


<!-- メイン画像 ここから -->
<div id="header-img">
<img src="img/head_img_slim.png" alt="head_img_slim" class="main_photo">
</div>
<!-- メイン画像 ここまで -->




<!-- ヘッダー終わり -->


<!-- コンテンツ -->

<!-- メインコンテンツ -->

<div id="container">
  <div id="contents">


<div id="pannavi">
<a href="index.html">HOME</a> &gt; よくあるご質問ページ
</div>




<h2 class="page_title">よくあるご質問</h2>


<h3>よくあるご質問１</h3>

<p>こちらには、よくいただく質問を記載してください。</p>

<hr class="line">

<p>&nbsp;</p>







<h2>お問い合わせはコチラ</h2>

<div class="gray_bg_contact">

<p><img src="img/icon.gif" alt="icon"> <b>電話番号</b>： <span class="red_b">00-0000-0000</span>　<img src="img/icon.gif" alt="icon"> <b>FAX</b>： <span class="red_b">00-0000-0000</span><br>
ご不明な点がございましたら、まずはお気軽にご相談下さい。<br>
<b><a href="contact.html">→メールでのお問い合わせ</a></b></p>

</div>






<hr class="line">

<p class="back"><a href="#header"><img class="scroll" src="img/pagetop.png" alt="ページトップに戻る"></a></p>

<br>


  </div>

<!-- メインコンテンツ終わり -->

</div>

<!-- コンテンツ終わり -->

<!-- フッター -->

<div id="footer">
<a href="index.html">ホーム</a>　|　<a href="goaisatu.html">ご挨拶</a>　|　<a href="information.html">業務内容</a>　|　<a href="profile.html">会社概要</a>　|　<a href="faq.html">よくあるご質問</a>　|　<a href="contact.html">お問い合わせ</a>　|　<a href="link.html">リンク</a>　|　<a href="sitemap.html">サイトマップ</a>
<br>
<br>
Copyright (C) 20xx SITE NAME All Rights Reserved.　design by <a href="http://tempnate.com/" target="_blank">tempnate</a>
</div>

<!-- フッター終わり -->

</div>

<!-- メイン終わり -->

</body>
</html>

main/templates/main/goaisatu.html
<!DOCTYPE HTML>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>ホームページ・タイトル</title>
<meta name="viewport" content="width=device-width">
<meta name="keywords" content="キーワード">
<meta name="description" content="紹介文">
<link rel="stylesheet" href="css/sp.css">
<link rel="stylesheet" href="css/pc.css">
<!--[if lt IE 9]>
<script src="js/html5.js"></script>
<script src="js/css3-mediaqueries.js"></script>
<![endif]-->

</head>

<body>

<!-- メイン -->

<div id="main">


<!-- ヘッダー -->

<div id="header">

<h1>こちらには、メインキーワードや紹介文を入れてください</h1>

  <div id="header_inner">
   <div id="h_logo"><h2><a href="index.html">テンプレートカンパニー</a></h2></div>
   <div id="h_info">
<p class="tel">TEL. 00-0000-0000</p>
<p>営業時間 AM10:00 ～ PM20:00</p>
</div>
  </div>

</div>

<div id="header-menu">
  <ul class="clearfix">
    <li class="home"><a href="index.html">ホーム<br /><span class="sub">home</span></a></li>
    <li><a href="goaisatu.html">ご挨拶<br /><span class="sub">goaisatu</span></a></li>
    <li><a href="information.html">業務内容<br /><span class="sub">infomation</span></a></li>
    <li><a href="profile.html">会社概要<br /><span class="sub">profile</span></a></li>
    <li><a href="faq.html">よくあるご質問<br /><span class="sub">faq</span></a></li>
    <li><a href="contact.html">お問い合わせ<br /><span class="sub">contact</span></a></li>
   </ul>
</div>


<!-- メイン画像 ここから -->
<div id="header-img">
<img src="img/head_img_slim.png" alt="head_img_slim" class="main_photo">
</div>
<!-- メイン画像 ここまで -->




<!-- ヘッダー終わり -->


<!-- コンテンツ -->

<!-- メインコンテンツ -->

<div id="container">
  <div id="contents">


<div id="pannavi">
<a href="index.html">HOME</a> &gt; ごあいさつのページ
</div>




<h2 class="page_title">ごあいさつ</h2>

<p>こちらには、ごあいさつなどを記載してください。</p>

<hr class="line">

<p>&nbsp;</p>







<h2>お問い合わせはコチラ</h2>

<div class="gray_bg_contact">

<p><img src="img/icon.gif" alt="icon"> <b>電話番号</b>： <span class="red_b">00-0000-0000</span>　<img src="img/icon.gif" alt="icon"> <b>FAX</b>： <span class="red_b">00-0000-0000</span><br>
ご不明な点がございましたら、まずはお気軽にご相談下さい。<br>
<b><a href="contact.html">→メールでのお問い合わせ</a></b></p>

</div>






<hr class="line">

<p class="back"><a href="#header"><img class="scroll" src="img/pagetop.png" alt="ページトップに戻る"></a></p>

<br>


  </div>

<!-- メインコンテンツ終わり -->

</div>

<!-- コンテンツ終わり -->

<!-- フッター -->

<div id="footer">
<a href="index.html">ホーム</a>　|　<a href="goaisatu.html">ご挨拶</a>　|　<a href="information.html">業務内容</a>　|　<a href="profile.html">会社概要</a>　|　<a href="faq.html">よくあるご質問</a>　|　<a href="contact.html">お問い合わせ</a>　|　<a href="link.html">リンク</a>　|　<a href="sitemap.html">サイトマップ</a>
<br>
<br>
Copyright (C) 20xx SITE NAME All Rights Reserved.　design by <a href="http://tempnate.com/" target="_blank">tempnate</a>
</div>

<!-- フッター終わり -->

</div>

<!-- メイン終わり -->

</body>
</html>

main/templates/main/header.html
{% load static %}
<!-- メイン -->
<div id="main">
    <!-- ヘッダー -->
    <div id="header">
        <h1>こちらには、メインキーワードや紹介文を入れてください</h1>
        <div id="header_inner">
            <div id="h_logo">
                <h2><a href="{% url 'main:index' %}">あなたも里親</a></h2>
            </div>
            <div id="h_info">
                <p class="tel">TEL. 00-0000-0000</p>
                <p>営業時間 AM10:00 ～ PM20:00</p>
            </div>
        </div>
    </div>

    <div class="container-class">
        <div class="contens-class">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-3 prefectures-menu menu-top none-link"><a>北海道</a></div>
                    <div class="col-sm-3 prefectures-menu none-link"><a>東北</a></div>
                    <div class="col-sm-3 prefectures-menu"><a href="{% url 'main:kanto' %}">関東</a></div>
                    <div class="col-sm-3 prefectures-menu none-link"><a>中部</a></div>
                </div>
                <div class="row">
                    <div class="col-sm-3 prefectures-menu menu-top none-link"><a>近畿</a></div>
                    <div class="col-sm-3 prefectures-menu none-link"><a>中国</a></div>
                    <div class="col-sm-3 prefectures-menu none-link"><a>四国</a></div>
                    <div class="col-sm-3 prefectures-menu none-link"><a>九州</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
<hr class="line">
<!-- メイン画像 ここから -->
<div id="header-img">
    <img src="{% static 'main/img/top/IMG_2708_cut.JPG' %}" width=100% height="490" alt="head_img" class="main_photo">
    <p>You are also a foster parent.</p>
</div>
<hr class="line">

<!-- 肉球のマークを入れる -->

main/templates/main/index.html
{% load static %}
<!DOCTYPE HTML>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>ホームページ・タイトル</title>
<meta name="viewport" content="width=device-width">
<meta name="keywords" content="キーワード">
<meta name="description" content="紹介文">

<!-- BootstrapのCSS読み込み -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"><!-- jQuery読み込み -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- BootstrapのJS読み込み -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<!-- <link rel="stylesheet" href="css/sp.css">
<link rel="stylesheet" href="css/pc.css"> -->
<link rel="stylesheet" href="{% static 'main/css/sp.css' %}">
<link rel="stylesheet" href="{% static 'main/css/pc.css' %}">

<!--[if lt IE 9]>
<script src="js/html5.js"></script>
<script src="js/css3-mediaqueries.js"></script>
<![endif]-->


</head>

<body>
  <div id="main-menu"></div>
  {% include 'main/header.html' %}
<!--  <script>
    $(function () {
      $("#main-menu").load("{% static 'main/templates/header.html' %}");
    });
  </script> -->

<!-- ヘッダー終わり -->


<!-- コンテンツ -->

<div class="main-contents">
  <div class="prefectures-title">
    <h2 class="subtitle">今日の気まぐれ猫</h2>
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2 px-0 cats-image">
        <a href="javascript:ImageUp();"><img src="{% static 'main/img_ori/cat_A.jpeg' %}" width="170" height="140" alt="猫"></a>
      </div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="{% static 'main/img_ori/cat_B.jpg' %}"  width="170" height="140" alt="猫"></a></div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="{% static 'main/img_ori/cat_C.jpg' %}"  width="170" height="140" alt="猫"></a></div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="{% static 'main/img_ori/cat_D.jpeg' %}" width="170" height="140" alt="猫"></a></div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="{% static 'main/img_ori/cat_D.jpeg' %}" width="170" height="140" alt="猫"></a></div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="{% static 'main/img_ori/cat_D.jpeg' %}" width="170" height="140" alt="猫"></a></div>
    </div>
  </div>

  <hr class="line">
  <div class="introduction">
      <h2 class="subtitle">このサイトについて</h2>
    <!-- <div class="gray_bg_contact"> -->
    <p>
      このサイトは保護猫の里親募集情報を色々なサイトより収集し、掲載しています。<br>
      多くの猫の幸せのためにと思い、このサイトを立ち上げました。<br>
      保護された猫たちが、どうか少しでも、良い里親さんの元にたどり着けますように。<br>
    </p>
    <!-- </div> -->
    <hr class="line">
  </div>

  <div class="information">
    <h2 class="subtitle">最新情報＆更新情報</h2>
    <div id="news">
      <pre class="news-text">2023.4.10  webサイトを公開しました。</pre>
      <hr class="line">
      20xx.3.26 <a href="#">新サービスについてのプレスリリースをご覧ください。</a><br>
      <hr class="line">
      20xx.3.10 <a href="#">天賦会館でセミナーを行ないました。</a><br>
      <hr class="line">
      20xx.3.08 <a href="#">会社概要ページを更新しました。</a><br>
      <hr class="line">
    </div>
    <hr class="line">
  </div>

  <div class="inquiry">
    <h2 class="subtitle">お問い合わせはコチラ</h2>
    <div class="gray_bg_contact">
      <p><img src="{% static 'main/img/icon.gif' %}" alt="icon"> <b>電話番号</b>： <span class="red_b">00-0000-0000</span>　<img src="{% static 'main/img/icon.gif' %}" alt="icon"> 
      <b>FAX</b>： <span class="red_b">00-0000-0000</span><br>
      ご不明な点がございましたら、まずはお気軽にご相談下さい。<br>
      <b><a href="contact.html">→メールでのお問い合わせ</a></b></p>
    </div>
  </div>
</div>

<hr class="line">

<p>&nbsp;</p>


















<p class="back"><a href="#header"><img class="scroll" src="{% static 'main/img/pagetop.png' %}" alt="ページトップに戻る"></a></p>


  </div>

<!-- メインコンテンツ終わり -->

</div>

<!-- コンテンツ終わり -->

<!-- フッター -->

<div id="footer">
<a href="index.html">ホーム</a>　|　<a href="goaisatu.html">ご挨拶</a>　|　<a href="information.html">業務内容</a>　|　<a href="profile.html">会社概要</a>　|　<a href="faq.html">よくあるご質問</a>　|　<a href="contact.html">お問い合わせ</a>　|　<a href="link.html">リンク</a>　|　<a href="sitemap.html">サイトマップ</a>
<br>
<br>
Copyright (C) 20xx SITE NAME All Rights Reserved.　design by <a href="http://tempnate.com/" target="_blank">tempnate</a>
</div>

<!-- フッター終わり -->

</div>

<!-- メイン終わり -->

</body>
</html>

main/templates/main/kanto.html
{% load static %}
<!DOCTYPE HTML>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>ホームページ・タイトル</title>
<meta name="viewport" content="width=device-width">
<meta name="keywords" content="キーワード">
<meta name="description" content="紹介文">

<!-- BootstrapのCSS読み込み -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"><!-- jQuery読み込み -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- BootstrapのJS読み込み -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<!-- 独自CSS の読み込み -->
<link rel="stylesheet" href="{% static 'main/css/sp.css' %}">
<link rel="stylesheet" href="{% static 'main/css/pc.css' %}">

<script>
  function ImageUp() {
    window.open("https://www.pet-home.jp/cats/saitama/pn461337/","window1","width=750,height=1000,scrollbars=1");
  }
</script>

</head>

<body>
 <div id="main-menu"></div>
 {% include 'main/header.html' %}
<!-- ヘッダー終わり -->


<!-- コンテンツ -->

<!-- メインコンテンツ -->

<div class="main-contents">
  <div class="prefectures-title"><h3>東京</h3></div>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2 px-0 cats-image">
        <a href="javascript:ImageUp();"><img src="img_ori/cat_A.jpeg" width="170" height="140" alt="猫"></a>
      </div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="img_ori/cat_B.jpg"  width="170" height="140" alt="猫"></a></div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="img_ori/cat_C.jpg"  width="170" height="140" alt="猫"></a></div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="img_ori/cat_D.jpeg" width="170" height="140" alt="猫"></a></div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="img_ori/cat_D.jpeg" width="170" height="140" alt="猫"></a></div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="img_ori/cat_D.jpeg" width="170" height="140" alt="猫"></a></div>
    </div>
    <div class="row">
      <div class="col-sm-2 px-0 cats-image"><a><img src="img_ori/cat_E.jpeg" width="170" height="140" alt="猫"></a></div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="img_ori/cat_F.jpeg" width="170" height="140" alt="猫"></a></div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="img_ori/cat_G.jpeg" width="170" height="140" alt="猫"></a></div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="img_ori/cat_H.jpeg" width="170" height="140" alt="猫"></a></div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="img_ori/cat_D.jpeg" width="170" height="140" alt="猫"></a></div>
      <div class="col-sm-2 px-0 cats-image"><a><img src="img_ori/cat_D.jpeg" width="170" height="140" alt="猫"></a></div>
    </div>
  </div>


</div>




<h2>業務内容1　（画像の回り込み方法１）</h2>

<p><img class="picture" src="img/photo_01.jpg" alt="photo">
画像の横にテキストを回り込みで指定しています。imgタグの中に（ class="picture" ）を入れると、画像の横にテキストを回り込ませる事ができます。</p>

<p>テキストの最後に（ br class="clear" ）というタグを入れると、テキストの回り込みを解除できます。これを入れないと下↓の見出しがずれます。<br class="clear"></p>

<hr class="line">

<p>&nbsp;</p>





<h2>業務内容1　（画像の回り込み方法１）</h2>

<p><img class="picture" src="img/photo_01.jpg" alt="photo">
画像の横にテキストを回り込みで指定しています。imgタグの中に（ class="picture" ）を入れると、画像の横にテキストを回り込ませる事ができます。</p>

<p>テキストの最後に（ br class="clear" ）というタグを入れると、テキストの回り込みを解除できます。これを入れないと下↓の見出しがずれます。<br class="clear"></p>

<hr class="line">

<p>&nbsp;</p>





<h2>業務内容3</h2>

<table>
<tr>
<td class="t00">
  <table class="t01">
  <tr>
   <td class="head">業務内容・タイトル１</td>
  </tr>
  <tr>
   <td class="t01"><img class="picture" src="img/photo_02.jpg" alt="photo">２列のレイアウトです。ホームページビルダーなどで、配置したい所にご利用ください。<br class="clear"></td>
  </tr>
  </table>
</td>
<td>
  <table class="t01">
  <tr>
   <td class="head">業務内容・タイトル２</td>
  </tr>
  <tr>
   <td class="t01"><img class="picture" src="img/photo_02.jpg" alt="photo">テーブルタグで指定しています。画像も入れ替えてください。画像は110px x 100pxです。<br class="clear"></td>
  </tr>
  </table>
</td>

</tr>
</table>

<p>&nbsp;</p>





<h2>業務内容4</h2>

<h3>小見出しタイトル</h3>

<p>ホームページ作成ソフトをご利用の際は、この見出し↑の前後をコピーして、下に貼り付けで増やしていってください。</p>

<hr class="line">

<p>&nbsp;</p>







<h2>お問い合わせはコチラ</h2>

<div class="gray_bg_contact">

<p><img src="img/icon.gif" alt="icon"> <b>電話番号</b>： <span class="red_b">00-0000-0000</span>　<img src="img/icon.gif" alt="icon"> <b>FAX</b>： <span class="red_b">00-0000-0000</span><br>
ご不明な点がございましたら、まずはお気軽にご相談下さい。<br>
<b><a href="contact.html">→メールでのお問い合わせ</a></b></p>

</div>






<hr class="line">

<p class="back"><a href="#header"><img class="scroll" src="img/pagetop.png" alt="ページトップに戻る"></a></p>

<br>


  </div>

<!-- メインコンテンツ終わり -->

</div>

<!-- コンテンツ終わり -->

<!-- フッター -->

<div id="footer">
<a href="index.html">ホーム</a>　|　<a href="goaisatu.html">ご挨拶</a>　|　<a href="information.html">業務内容</a>　|　<a href="profile.html">会社概要</a>　|　<a href="faq.html">よくあるご質問</a>　|　<a href="contact.html">お問い合わせ</a>　|　<a href="link.html">リンク</a>　|　<a href="sitemap.html">サイトマップ</a>
<br>
<br>
Copyright (C) 20xx SITE NAME All Rights Reserved.　design by <a href="http://tempnate.com/" target="_blank">tempnate</a>
</div>

<!-- フッター終わり -->

</div>

<!-- メイン終わり -->

</body>
</html>